# -*- mode: ruby -*-
# vi: set ft=ruby :

WEBSERVER_IP = "192.168.56.11"
DATABASE_IP = "192.168.56.12"
RAM = 512
CPUs = 1

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "webbserver" do |web|
    web.vm.hostname = "webserver"

    web.vm.network "private_network", ip: WEBSERVER_IP
    web.vm.network "forwarded_port", guest: 80, host: 8080

    web.vm.provider "virtualbox" do |vb|
      vb.name = "webbserver3"
      vb.memory = RAM
      vb.cpus = CPUs
    end
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install -y apache2 iputils-ping netcat-openbsd
      systemctl enable apache2
      systemctl start apache2
      echo "<h1>Webbserver: $(hostname)</h1>" > /var/www/html/index.html
      echo "=== Webbserver Klar ==="
    SHELL
  end
  config.vm.define "database" do |db|
    db.vm.hostname = "database"

    db.vm.network "private_network", ip: DATABASE_IP

    db.vm.provider "virtualbox" do |vb|
      vb.name = "database3"
      vb.memory = RAM
      vb.cpus = CPUs

      db.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        apt-get install -y postgresql iputils-ping ufw
        systemctl enable postgresql
        systemctl start postgresql
        ufw default deny incoming 
        ufw default allow outgoing 
        ufw allow ssh
        ufw allow form 192.168.56.11 to any port 5432
        ufw --force enable 
        echo "=== Databesserver Klar ==="
      SHELL
    end
end
