# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM_512mb = 512
RAM_1024mb = 1024
CPU = 1
WEBSERVER_IP = "192.168.56.10"
DBSERVER_IP = "192.168.56.11"

Vagrant.configure("2") do |config|
  
  #========================================================================================================================================================================#
  # Creats a VM named webserver_vm1 with the ubunto as OS with port forwarding of port 8080 and privet network ip of 192.168.56.10 to make VM to VM communication possible #
  #========================================================================================================================================================================#
  config.vm.define "web" do |web_vm1|
    web_vm1.vm.box = "ubuntu/jammy64"
    web_vm1.vm.network "forwarded_port", guest: 80, host: 8080
    web_vm1.vm.network "private_network", ip: WEBSERVER_IP
    # ---- Syncs the folder the vagrantfile is in with the VM ----
    web_vm1.vm.synced_folder ".", "/vagrant"
    #====================================================================================================#
    # Allocates 512mb of RAM and 1 CPU core to the VM, Also sets the name of the VM and sets gui to fals #
    #====================================================================================================#
    web_vm1.vm.provider "virtualbox" do |vb|
      vb.name = "webserver_vm1"
      vb.memory = RAM_512mb
      vb.cpus = CPU
      vb.gui = false #headles
    end

    #===================================================================================================#
    # Auto uppdates and installs apache2 on the VM and replaces the defult index.html with a custom one #
    #===================================================================================================#
    web_vm1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
      # installs mysql-client to allow the webserver connect to the VM
      apt-get install -y mysql-client
      # installs an extension to apache2 that allows it to run php code
      apt-get install -y php libapache2-mod-php php-mysql

      systemctl enable apache2
      systemctl start apache2

      # removes the defult index.html becous it has priority over the php filles
      sudo rm -f /var/www/html/index.html

      # inserts the index.php fille form the sheard folder to a internal folder in the VM
      sudo cp /vagrant/index.php /var/www/html/index.php

      echo -e "\e[32m=================================\e[0m"
      echo -e "\e[32m     WEBBSERVER_VM1 ONLINE       \e[0m"
      echo -e "\e[32m=================================\e[0m"
    SHELL
  end
  

  #=====================================================================================================================================#
  # Creats a VM named database_vm2 with the ubunto as OS and privet network ip of 192.168.56.11 to make VM to VM communication possible #
  #=====================================================================================================================================#
  config.vm.define "db" do |db_vm3|
    db_vm3.vm.box = "ubuntu/jammy64"
    db_vm3.vm.network "private_network", ip: DBSERVER_IP
    #======================================================================================================#
    # Allocates 1024mb of RAM and 1 CPU core to the VM, Also sets the name of the VM and sets gui to false # 
    #======================================================================================================#
    db_vm3.vm.provider "virtualbox" do |vb|
      vb.name = "database_vm2"
      vb.memory = RAM_1024mb
      vb.cpus = CPU
      vb.gui = false #headles
    end

    #==================================================================================================#
    # Installs and updates every thing that is need to make this VM a db automaticly on boot of the VM #
    #==================================================================================================#
    db_vm3.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y mysql-server

      sed -i 's/^bind-address.*/bind-address = 192.168.56.11/' /etc/mysql/mysql.conf.d/mysqld.cnf
      
      systemctl enable mysql
      systemctl restart mysql

      # waits 5 secounds to make sure mysql is started
      sleep 5

      # Creats a user and gives it full privileges
      sudo mysql -e "CREATE USER 'testuser'@'192.168.56.10' IDENTIFIED BY 'testpass';"
      sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'192.168.56.10';"
      sudo mysql -e "FLUSH PRIVILEGES;"

      # Creats a sql data base on boot with the tables timestamp, server_name and ip
      sudo mysql -e "CREATE DATABASE webdb;"
      sudo mysql -e "USE webdb; CREATE TABLE visits (
        id INT AUTO_INCREMENT PRIMARY KEY,
        timestamp DATETIME,
        server_name VARCHAR(50),
        ip VARCHAR(50)
      );"

      echo -e "\e[32m=================================\e[0m"
      echo -e "\e[32m      DBSERVER_VM2 ONLINE        \e[0m"
      echo -e "\e[32m=================================\e[0m"
      
    SHELL
  end
end
