# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #===================================================================================================================#
  # Creats a VM named webserver with the ubunto as OS with port forwarding of port 8080 and has the ip 192.168.56.10  #
  #===================================================================================================================#
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/jammy64"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    #====================================================================================================#
    # Allocates 512mb of RAM and 1 CPU core to the VM, Also sets the name of the VM and sets gui to fals #
    #====================================================================================================#
    web.vm.provider "virtualbox" do |vb|
      vb.name = "webserver"
      vb.memory = 512
      vb.cpus = 1
      vb.gui = false #headles
    end
    #====================================================#
    # Auto uppdates and installs apache2 on the VM       #
    #====================================================#
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
    SHELL
  end
end
